[package]
name = "tmdb-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tmdb-config = { path = "../../crates/tmdb-config" }
tmdb-db = { path = "../../crates/tmdb-db" }
tmdb-jobs = { path = "../../crates/tmdb-jobs" }
tmdb-upstream = { path = "../../crates/tmdb-upstream" }
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
