-- Shared catalog identity, dimensions, relationships, and the first search-ready
-- projection.  This migration deliberately stops before seasons, people/credits,
-- classification history, translations, and image/source tables; those are separate
-- follow-up migrations so each rollout remains reviewable and reversible.

-- pg_trgm and unaccent are trusted extensions on the supported PostgreSQL 18 image.
-- The development bootstrap installs them, while this idempotent guard also lets the
-- SQLx test database be migrated from a clean template.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE catalog.titles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_type text NOT NULL,
    tmdb_id bigint NOT NULL,
    display_title text,
    original_title text,
    overview text,
    tagline text,
    status text,
    original_language text,
    release_date date,
    first_air_date date,
    last_air_date date,
    popularity double precision,
    vote_average double precision,
    vote_count bigint,
    runtime_minutes integer,
    adult boolean NOT NULL DEFAULT false,
    video boolean NOT NULL DEFAULT false,
    homepage text,
    poster_path text,
    backdrop_path text,
    is_anime boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    source_updated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT titles_media_type_check CHECK (media_type IN ('movie', 'tv')),
    CONSTRAINT titles_tmdb_id_check CHECK (tmdb_id > 0),
    CONSTRAINT titles_original_language_check
        CHECK (original_language IS NULL OR char_length(original_language) BETWEEN 1 AND 16),
    CONSTRAINT titles_popularity_check CHECK (popularity IS NULL OR popularity >= 0),
    CONSTRAINT titles_vote_average_check
        CHECK (vote_average IS NULL OR vote_average BETWEEN 0 AND 10),
    CONSTRAINT titles_vote_count_check CHECK (vote_count IS NULL OR vote_count >= 0),
    CONSTRAINT titles_runtime_check CHECK (runtime_minutes IS NULL OR runtime_minutes >= 0),
    CONSTRAINT titles_identity_unique UNIQUE (media_type, tmdb_id),
    CONSTRAINT titles_id_media_type_unique UNIQUE (id, media_type)
);

CREATE TABLE catalog.movie_details (
    title_id bigint NOT NULL,
    media_type text NOT NULL DEFAULT 'movie',
    budget bigint,
    revenue bigint,
    runtime_minutes integer,
    imdb_id text,
    collection_id bigint,
    CONSTRAINT movie_details_pkey PRIMARY KEY (title_id),
    CONSTRAINT movie_details_media_type_check CHECK (media_type = 'movie'),
    CONSTRAINT movie_details_budget_check CHECK (budget IS NULL OR budget >= 0),
    CONSTRAINT movie_details_revenue_check CHECK (revenue IS NULL OR revenue >= 0),
    CONSTRAINT movie_details_runtime_check
        CHECK (runtime_minutes IS NULL OR runtime_minutes >= 0),
    CONSTRAINT movie_details_title_fkey
        FOREIGN KEY (title_id, media_type)
        REFERENCES catalog.titles (id, media_type) ON DELETE CASCADE
);

CREATE TABLE catalog.tv_details (
    title_id bigint NOT NULL,
    media_type text NOT NULL DEFAULT 'tv',
    in_production boolean,
    number_of_episodes integer,
    number_of_seasons integer,
    series_type text,
    CONSTRAINT tv_details_pkey PRIMARY KEY (title_id),
    CONSTRAINT tv_details_media_type_check CHECK (media_type = 'tv'),
    CONSTRAINT tv_details_episode_count_check
        CHECK (number_of_episodes IS NULL OR number_of_episodes >= 0),
    CONSTRAINT tv_details_season_count_check
        CHECK (number_of_seasons IS NULL OR number_of_seasons >= 0),
    CONSTRAINT tv_details_title_fkey
        FOREIGN KEY (title_id, media_type)
        REFERENCES catalog.titles (id, media_type) ON DELETE CASCADE
);

CREATE TABLE catalog.genres (
    id bigint PRIMARY KEY,
    name text,
    CONSTRAINT genres_id_check CHECK (id > 0),
    CONSTRAINT genres_name_check CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE TABLE catalog.keywords (
    id bigint PRIMARY KEY,
    name text,
    CONSTRAINT keywords_id_check CHECK (id > 0),
    CONSTRAINT keywords_name_check CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE TABLE catalog.tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    CONSTRAINT tags_name_check CHECK (btrim(name) <> ''),
    CONSTRAINT tags_name_unique UNIQUE (name)
);

CREATE TABLE catalog.companies (
    id bigint PRIMARY KEY,
    name text,
    origin_country text,
    logo_path text,
    CONSTRAINT companies_id_check CHECK (id > 0),
    CONSTRAINT companies_name_check CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE TABLE catalog.networks (
    id bigint PRIMARY KEY,
    name text,
    origin_country text,
    logo_path text,
    CONSTRAINT networks_id_check CHECK (id > 0),
    CONSTRAINT networks_name_check CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE TABLE catalog.languages (
    iso_639_1 text PRIMARY KEY,
    english_name text,
    name text,
    CONSTRAINT languages_code_check CHECK (char_length(iso_639_1) BETWEEN 2 AND 3)
);

CREATE TABLE catalog.countries (
    iso_3166_1 text PRIMARY KEY,
    name text,
    CONSTRAINT countries_code_check CHECK (char_length(iso_3166_1) BETWEEN 2 AND 3)
);

CREATE TABLE catalog.collections (
    id bigint PRIMARY KEY,
    name text,
    poster_path text,
    backdrop_path text,
    CONSTRAINT collections_id_check CHECK (id > 0),
    CONSTRAINT collections_name_check CHECK (name IS NULL OR btrim(name) <> '')
);

CREATE TABLE catalog.title_genres (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    genre_id bigint NOT NULL REFERENCES catalog.genres (id) ON DELETE RESTRICT,
    PRIMARY KEY (title_id, genre_id)
);

CREATE TABLE catalog.title_keywords (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    keyword_id bigint NOT NULL REFERENCES catalog.keywords (id) ON DELETE RESTRICT,
    PRIMARY KEY (title_id, keyword_id)
);

CREATE TABLE catalog.title_tags (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    tag_id bigint NOT NULL REFERENCES catalog.tags (id) ON DELETE RESTRICT,
    PRIMARY KEY (title_id, tag_id)
);

CREATE TABLE catalog.title_companies (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES catalog.companies (id) ON DELETE RESTRICT,
    company_role text,
    PRIMARY KEY (title_id, company_id)
);

CREATE TABLE catalog.title_networks (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    network_id bigint NOT NULL REFERENCES catalog.networks (id) ON DELETE RESTRICT,
    PRIMARY KEY (title_id, network_id)
);

CREATE TABLE catalog.title_languages (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    language_id text NOT NULL REFERENCES catalog.languages (iso_639_1) ON DELETE RESTRICT,
    is_original boolean NOT NULL DEFAULT false,
    PRIMARY KEY (title_id, language_id)
);

CREATE TABLE catalog.title_countries (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    country_id text NOT NULL REFERENCES catalog.countries (iso_3166_1) ON DELETE RESTRICT,
    is_origin boolean NOT NULL DEFAULT false,
    PRIMARY KEY (title_id, country_id)
);

CREATE TABLE catalog.title_collections (
    title_id bigint PRIMARY KEY REFERENCES catalog.titles (id) ON DELETE CASCADE,
    collection_id bigint NOT NULL REFERENCES catalog.collections (id) ON DELETE RESTRICT
);

CREATE TABLE search.search_documents (
    title_id bigint NOT NULL REFERENCES catalog.titles (id) ON DELETE CASCADE,
    locale text NOT NULL DEFAULT '',
    title text,
    original_title text,
    aliases text NOT NULL DEFAULT '',
    overview text,
    normalized_title text NOT NULL DEFAULT '',
    normalized_original_title text NOT NULL DEFAULT '',
    normalized_aliases text NOT NULL DEFAULT '',
    search_vector tsvector NOT NULL DEFAULT ''::tsvector,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT search_documents_pkey PRIMARY KEY (title_id, locale),
    CONSTRAINT search_documents_locale_check
        CHECK (locale = btrim(locale) AND char_length(locale) <= 16)
);

CREATE OR REPLACE FUNCTION search.refresh_search_document()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, search
AS $function$
BEGIN
    NEW.normalized_title := lower(public.unaccent(coalesce(NEW.title, '')));
    NEW.normalized_original_title := lower(public.unaccent(coalesce(NEW.original_title, '')));
    NEW.normalized_aliases := lower(public.unaccent(coalesce(NEW.aliases, '')));
    NEW.search_vector :=
        setweight(to_tsvector('simple', public.unaccent(coalesce(NEW.title, ''))), 'A')
        || setweight(
            to_tsvector('simple', public.unaccent(coalesce(NEW.original_title, ''))),
            'A'
        )
        || setweight(to_tsvector('simple', public.unaccent(coalesce(NEW.aliases, ''))), 'B')
        || setweight(to_tsvector('simple', public.unaccent(coalesce(NEW.overview, ''))), 'C');
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END
$function$;

ALTER FUNCTION search.refresh_search_document() OWNER TO migrator;
REVOKE ALL ON FUNCTION search.refresh_search_document() FROM PUBLIC;

CREATE TRIGGER search_documents_refresh_vector
BEFORE INSERT OR UPDATE OF title, original_title, aliases, overview
ON search.search_documents
FOR EACH ROW EXECUTE FUNCTION search.refresh_search_document();

CREATE OR REPLACE FUNCTION catalog.sync_search_document()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, catalog, search
AS $function$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM search.search_documents WHERE title_id = OLD.id;
        RETURN OLD;
    END IF;

    INSERT INTO search.search_documents (
        title_id, locale, title, original_title, overview
    ) VALUES (
        NEW.id, '', NEW.display_title, NEW.original_title, NEW.overview
    )
    ON CONFLICT (title_id, locale) DO UPDATE SET
        title = EXCLUDED.title,
        original_title = EXCLUDED.original_title,
        overview = EXCLUDED.overview;
    RETURN NEW;
END
$function$;

ALTER FUNCTION catalog.sync_search_document() OWNER TO migrator;
REVOKE ALL ON FUNCTION catalog.sync_search_document() FROM PUBLIC;

CREATE TRIGGER titles_sync_search_document
AFTER INSERT OR UPDATE OF display_title, original_title, overview OR DELETE
ON catalog.titles
FOR EACH ROW EXECUTE FUNCTION catalog.sync_search_document();

-- Relationship indexes are title-first through each primary key and dimension-first
-- for facet filters.  Public list indexes are partial because all ordinary routes
-- exclude inactive and anime titles; the paired anime index powers the anime route.
CREATE INDEX titles_non_anime_popularity_idx
    ON catalog.titles (
        media_type,
        (coalesce(popularity, 0::double precision)) DESC,
        id DESC
    )
    WHERE active AND NOT is_anime;
CREATE INDEX titles_anime_popularity_idx
    ON catalog.titles (
        media_type,
        (coalesce(popularity, 0::double precision)) DESC,
        id DESC
    )
    WHERE active AND is_anime;
CREATE INDEX titles_non_anime_release_idx
    ON catalog.titles (media_type, release_date DESC NULLS LAST, id DESC)
    WHERE active AND NOT is_anime;

CREATE INDEX title_genres_genre_idx ON catalog.title_genres (genre_id, title_id);
CREATE INDEX title_keywords_keyword_idx ON catalog.title_keywords (keyword_id, title_id);
CREATE INDEX title_tags_tag_idx ON catalog.title_tags (tag_id, title_id);
CREATE INDEX title_companies_company_idx ON catalog.title_companies (company_id, title_id);
CREATE INDEX title_networks_network_idx ON catalog.title_networks (network_id, title_id);
CREATE INDEX title_languages_language_idx ON catalog.title_languages (language_id, title_id);
CREATE INDEX title_countries_country_idx ON catalog.title_countries (country_id, title_id);
CREATE INDEX title_collections_collection_idx
    ON catalog.title_collections (collection_id, title_id);

CREATE INDEX search_documents_search_vector_gin_idx
    ON search.search_documents USING gin (search_vector);
CREATE INDEX search_documents_normalized_title_trgm_idx
    ON search.search_documents USING gist (normalized_title gist_trgm_ops);

-- SQLx's disposable test databases run migrations as their owner, while production
-- runs them as `migrator`; pin ownership explicitly so trigger security-definers and
-- the default ACL contract behave identically in both environments.
ALTER TABLE catalog.titles OWNER TO migrator;
ALTER TABLE catalog.movie_details OWNER TO migrator;
ALTER TABLE catalog.tv_details OWNER TO migrator;
ALTER TABLE catalog.genres OWNER TO migrator;
ALTER TABLE catalog.keywords OWNER TO migrator;
ALTER TABLE catalog.tags OWNER TO migrator;
ALTER TABLE catalog.companies OWNER TO migrator;
ALTER TABLE catalog.networks OWNER TO migrator;
ALTER TABLE catalog.languages OWNER TO migrator;
ALTER TABLE catalog.countries OWNER TO migrator;
ALTER TABLE catalog.collections OWNER TO migrator;
ALTER TABLE catalog.title_genres OWNER TO migrator;
ALTER TABLE catalog.title_keywords OWNER TO migrator;
ALTER TABLE catalog.title_tags OWNER TO migrator;
ALTER TABLE catalog.title_companies OWNER TO migrator;
ALTER TABLE catalog.title_networks OWNER TO migrator;
ALTER TABLE catalog.title_languages OWNER TO migrator;
ALTER TABLE catalog.title_countries OWNER TO migrator;
ALTER TABLE catalog.title_collections OWNER TO migrator;
ALTER TABLE search.search_documents OWNER TO migrator;

UPDATE ops.service_metadata
SET value = jsonb_build_object(
        'revision', '0005',
        'migrated_at', to_char(
            clock_timestamp() AT TIME ZONE 'UTC',
            'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
        )
    ),
    updated_at = clock_timestamp()
WHERE key = 'schema';

CREATE OR REPLACE VIEW ops.readiness AS
SELECT metadata.value ->> 'revision' AS schema_revision,
       (metadata.value ->> 'migrated_at')::timestamptz AS migrated_at
FROM ops.service_metadata AS metadata
WHERE metadata.key = 'schema'
  AND metadata.value ->> 'revision' = '0005'
  AND (SELECT count(*) FROM ops._sqlx_migrations) = 5
  AND (
      SELECT array_agg(migration.version ORDER BY migration.version)
      FROM ops._sqlx_migrations AS migration
      WHERE migration.success
  ) = ARRAY[1, 2, 3, 4, 5]::bigint[]
  AND NOT EXISTS (
      SELECT 1
      FROM ops._sqlx_migrations AS migration
      WHERE NOT migration.success
  );

ALTER VIEW ops.readiness OWNER TO migrator;
REVOKE ALL ON TABLE ops.readiness
    FROM PUBLIC, api_job_submitter, ingest_writer, image_writer, monitor;
GRANT SELECT ON TABLE ops.readiness TO api_reader, monitor;
