-- Core TMDB parity facets, verified responsive-media metadata, and bounded
-- component liveness.  These tables intentionally contain no credentials,
-- raw request headers, host paths, or arbitrary operator input.

CREATE TABLE catalog.title_translations (
    title_id bigint NOT NULL REFERENCES catalog.titles(id) ON DELETE CASCADE,
    language_code text NOT NULL,
    country_code text NOT NULL DEFAULT '',
    name text,
    overview text,
    tagline text,
    homepage text,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (title_id, language_code, country_code),
    CONSTRAINT title_translations_language_check CHECK (
        language_code ~ '^[a-z]{2,3}$'
    ),
    CONSTRAINT title_translations_country_check CHECK (
        country_code = '' OR country_code ~ '^[A-Z]{2}$'
    ),
    CONSTRAINT title_translations_text_check CHECK (
        (name IS NULL OR pg_catalog.char_length(name) <= 2_048)
        AND (overview IS NULL OR pg_catalog.char_length(overview) <= 32_768)
        AND (tagline IS NULL OR pg_catalog.char_length(tagline) <= 2_048)
        AND (homepage IS NULL OR pg_catalog.char_length(homepage) <= 2_048)
    )
);

CREATE TABLE catalog.title_alternate_titles (
    title_id bigint NOT NULL REFERENCES catalog.titles(id) ON DELETE CASCADE,
    title text NOT NULL,
    country_code text NOT NULL DEFAULT '',
    title_type text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (title_id, title, country_code, title_type),
    CONSTRAINT title_alternate_titles_title_check CHECK (
        pg_catalog.char_length(title) BETWEEN 1 AND 2_048
    ),
    CONSTRAINT title_alternate_titles_country_check CHECK (
        country_code = '' OR country_code ~ '^[A-Z]{2}$'
    ),
    CONSTRAINT title_alternate_titles_type_check CHECK (
        pg_catalog.char_length(title_type) <= 128
    )
);

CREATE TABLE catalog.title_external_ids (
    title_id bigint PRIMARY KEY REFERENCES catalog.titles(id) ON DELETE CASCADE,
    imdb_id text,
    tvdb_id text,
    wikidata_id text,
    facebook_id text,
    instagram_id text,
    twitter_id text,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT title_external_ids_length_check CHECK (
        (imdb_id IS NULL OR pg_catalog.char_length(imdb_id) <= 128)
        AND (tvdb_id IS NULL OR pg_catalog.char_length(tvdb_id) <= 128)
        AND (wikidata_id IS NULL OR pg_catalog.char_length(wikidata_id) <= 128)
        AND (facebook_id IS NULL OR pg_catalog.char_length(facebook_id) <= 128)
        AND (instagram_id IS NULL OR pg_catalog.char_length(instagram_id) <= 128)
        AND (twitter_id IS NULL OR pg_catalog.char_length(twitter_id) <= 128)
    )
);

CREATE TABLE catalog.title_videos (
    title_id bigint NOT NULL REFERENCES catalog.titles(id) ON DELETE CASCADE,
    video_key text NOT NULL,
    site text NOT NULL,
    video_type text,
    name text,
    official boolean NOT NULL DEFAULT false,
    language_code text,
    country_code text,
    published_at timestamptz,
    size integer,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (title_id, video_key),
    CONSTRAINT title_videos_key_check CHECK (
        pg_catalog.char_length(video_key) BETWEEN 1 AND 128
        AND video_key !~ '[[:cntrl:]]'
    ),
    CONSTRAINT title_videos_site_check CHECK (
        pg_catalog.char_length(site) BETWEEN 1 AND 64
        AND site !~ '[[:cntrl:]]'
    ),
    CONSTRAINT title_videos_text_check CHECK (
        (video_type IS NULL OR pg_catalog.char_length(video_type) <= 128)
        AND (name IS NULL OR pg_catalog.char_length(name) <= 2_048)
        AND (language_code IS NULL OR language_code ~ '^[a-z]{2,3}$')
        AND (country_code IS NULL OR country_code ~ '^[A-Z]{2}$')
        AND (size IS NULL OR size BETWEEN 1 AND 16_384)
    )
);

CREATE TABLE catalog.title_release_dates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id bigint NOT NULL REFERENCES catalog.titles(id) ON DELETE CASCADE,
    country_code text NOT NULL,
    release_date timestamptz,
    certification text,
    release_type smallint,
    note text,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT title_release_dates_country_check CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT title_release_dates_certification_check CHECK (
        certification IS NULL OR pg_catalog.char_length(certification) <= 64
    ),
    CONSTRAINT title_release_dates_type_check CHECK (
        release_type IS NULL OR release_type BETWEEN 1 AND 16
    ),
    CONSTRAINT title_release_dates_note_check CHECK (
        note IS NULL OR pg_catalog.char_length(note) <= 2_048
    ),
    CONSTRAINT title_release_dates_identity_unique UNIQUE NULLS NOT DISTINCT (
        title_id, country_code, release_date, release_type, certification, note
    )
);

CREATE INDEX title_translations_lookup_idx
    ON catalog.title_translations (title_id, language_code, country_code);
CREATE INDEX title_alternate_titles_lookup_idx
    ON catalog.title_alternate_titles (title_id, country_code, title);
CREATE INDEX title_videos_lookup_idx
    ON catalog.title_videos (title_id, site, video_type, published_at DESC NULLS LAST);
CREATE INDEX title_release_dates_lookup_idx
    ON catalog.title_release_dates (title_id, country_code, release_date DESC NULLS LAST, id);

CREATE TABLE catalog.title_trends (
    trend_window text NOT NULL,
    media_type text NOT NULL,
    title_id bigint NOT NULL REFERENCES catalog.titles(id) ON DELETE CASCADE,
    rank integer NOT NULL,
    score double precision,
    collected_for date NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (trend_window, media_type, title_id),
    CONSTRAINT title_trends_window_check CHECK (trend_window IN ('day', 'week')),
    CONSTRAINT title_trends_media_type_check CHECK (media_type IN ('movie', 'tv')),
    CONSTRAINT title_trends_rank_check CHECK (rank BETWEEN 1 AND 10_000),
    CONSTRAINT title_trends_score_check CHECK (
        score IS NULL
        OR (score = score AND score <> 'Infinity'::double precision AND score <> '-Infinity'::double precision)
    )
);

CREATE INDEX title_trends_public_order_idx
    ON catalog.title_trends (trend_window, media_type, collected_for DESC, rank, title_id);

CREATE TABLE assets.image_variants (
    image_asset_id bigint NOT NULL REFERENCES assets.image_assets(id) ON DELETE CASCADE,
    variant_key text NOT NULL,
    storage_path text NOT NULL,
    mime_type text NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    file_size_bytes bigint NOT NULL,
    sha256 text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (image_asset_id, variant_key),
    CONSTRAINT image_variants_key_check CHECK (variant_key ~ '^[a-z0-9_]{1,64}$'),
    CONSTRAINT image_variants_path_check CHECK (
        pg_catalog.char_length(storage_path) BETWEEN 1 AND 512
        AND storage_path !~ '[[:cntrl:]]'
        AND storage_path !~ '(^|/)\\.\\.?(/|$)'
        AND storage_path !~ '\\\\'
    ),
    CONSTRAINT image_variants_mime_check CHECK (mime_type IN ('image/jpeg', 'image/webp')),
    CONSTRAINT image_variants_dimensions_check CHECK (width > 0 AND height > 0),
    CONSTRAINT image_variants_size_check CHECK (file_size_bytes > 0),
    CONSTRAINT image_variants_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT image_variants_storage_unique UNIQUE (storage_path)
);

CREATE INDEX image_variants_asset_idx ON assets.image_variants (image_asset_id, variant_key);

CREATE TABLE ops.component_heartbeats (
    component text PRIMARY KEY,
    state text NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT component_heartbeats_component_check CHECK (
        component IN ('worker', 'media', 'upstream', 'backup')
    ),
    CONSTRAINT component_heartbeats_state_check CHECK (state IN ('ready', 'degraded', 'failed'))
);

CREATE FUNCTION ops.record_component_heartbeat(p_component text, p_state text)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ops, pg_temp
AS $function$
DECLARE
    v_observed_at timestamptz := pg_catalog.clock_timestamp();
BEGIN
    IF p_component NOT IN ('worker', 'media', 'upstream', 'backup')
       OR p_state NOT IN ('ready', 'degraded', 'failed') THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'component heartbeat rejected';
    END IF;
    INSERT INTO ops.component_heartbeats (component, state, observed_at)
    VALUES (p_component, p_state, v_observed_at)
    ON CONFLICT (component) DO UPDATE
    SET state = EXCLUDED.state,
        observed_at = EXCLUDED.observed_at;
    RETURN v_observed_at;
END
$function$;

ALTER TABLE catalog.title_translations OWNER TO migrator;
ALTER TABLE catalog.title_alternate_titles OWNER TO migrator;
ALTER TABLE catalog.title_external_ids OWNER TO migrator;
ALTER TABLE catalog.title_videos OWNER TO migrator;
ALTER TABLE catalog.title_release_dates OWNER TO migrator;
ALTER TABLE catalog.title_trends OWNER TO migrator;
ALTER TABLE assets.image_variants OWNER TO migrator;
ALTER TABLE ops.component_heartbeats OWNER TO migrator;
ALTER FUNCTION ops.record_component_heartbeat(text, text) OWNER TO migrator;

REVOKE ALL ON TABLE
    catalog.title_translations, catalog.title_alternate_titles, catalog.title_external_ids,
    catalog.title_videos, catalog.title_release_dates, catalog.title_trends,
    assets.image_variants, ops.component_heartbeats
    FROM PUBLIC, api_reader, api_job_submitter, ingest_writer, image_writer, monitor;
REVOKE ALL ON FUNCTION ops.record_component_heartbeat(text, text)
    FROM PUBLIC, api_reader, api_job_submitter, ingest_writer, image_writer, monitor;
GRANT SELECT ON TABLE
    catalog.title_translations, catalog.title_alternate_titles, catalog.title_external_ids,
    catalog.title_videos, catalog.title_release_dates, catalog.title_trends,
    assets.image_variants, ops.component_heartbeats
    TO api_reader, monitor;
GRANT INSERT, UPDATE, DELETE ON TABLE
    catalog.title_translations, catalog.title_alternate_titles, catalog.title_external_ids,
    catalog.title_videos, catalog.title_release_dates, catalog.title_trends
    TO ingest_writer;
GRANT INSERT, UPDATE, DELETE ON TABLE assets.image_variants TO image_writer;
GRANT EXECUTE ON FUNCTION ops.record_component_heartbeat(text, text)
    TO ingest_writer, image_writer;

UPDATE ops.service_metadata
SET value = pg_catalog.jsonb_build_object(
        'revision', '0023',
        'migrated_at', pg_catalog.to_char(
            pg_catalog.clock_timestamp() AT TIME ZONE 'UTC',
            'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
        )
    ),
    updated_at = pg_catalog.clock_timestamp()
WHERE key = 'schema';

CREATE OR REPLACE VIEW ops.readiness AS
SELECT metadata.value ->> 'revision' AS schema_revision,
       (metadata.value ->> 'migrated_at')::timestamptz AS migrated_at
FROM ops.service_metadata AS metadata
WHERE metadata.key = 'schema'
  AND metadata.value ->> 'revision' = '0023'
  AND (SELECT pg_catalog.count(*) FROM ops._sqlx_migrations) = 23
  AND (
      SELECT pg_catalog.array_agg(migration.version ORDER BY migration.version)
      FROM ops._sqlx_migrations AS migration
      WHERE migration.success
  ) = ARRAY[
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
  ]::bigint[]
  AND NOT EXISTS (
      SELECT 1
      FROM ops._sqlx_migrations AS migration
      WHERE NOT migration.success
  );

ALTER VIEW ops.readiness OWNER TO migrator;
REVOKE ALL ON TABLE ops.readiness
    FROM PUBLIC, api_reader, api_job_submitter, ingest_writer, image_writer, monitor;
GRANT SELECT ON TABLE ops.readiness TO api_reader, monitor;
