-- Small local state tables for the TMDB v3 session, list, favorite,
-- watchlist, and rating operations.

CREATE TABLE source.tmdb_v3_request_tokens (
    token text PRIMARY KEY,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT tmdb_v3_request_tokens_token_check CHECK (
        pg_catalog.char_length(token) BETWEEN 1 AND 128
        AND token !~ '[[:cntrl:]]'
    ),
    CONSTRAINT tmdb_v3_request_tokens_expiry_check CHECK (expires_at > created_at)
);

CREATE TABLE source.tmdb_v3_sessions (
    session_id text PRIMARY KEY,
    account_id bigint,
    is_guest boolean NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT tmdb_v3_sessions_id_check CHECK (
        pg_catalog.char_length(session_id) BETWEEN 1 AND 128
        AND session_id !~ '[[:cntrl:]]'
    ),
    CONSTRAINT tmdb_v3_sessions_owner_check CHECK (is_guest OR account_id IS NOT NULL),
    CONSTRAINT tmdb_v3_sessions_expiry_check CHECK (expires_at > created_at)
);

CREATE TABLE source.tmdb_v3_lists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    language_code text NOT NULL DEFAULT 'en-US',
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT tmdb_v3_lists_name_check CHECK (
        pg_catalog.char_length(name) BETWEEN 1 AND 255
        AND name = pg_catalog.btrim(name)
        AND name !~ '[[:cntrl:]]'
    ),
    CONSTRAINT tmdb_v3_lists_description_check CHECK (
        pg_catalog.char_length(description) <= 1_000
        AND description !~ '[[:cntrl:]]'
    ),
    CONSTRAINT tmdb_v3_lists_language_check CHECK (
        pg_catalog.char_length(language_code) BETWEEN 2 AND 12
        AND language_code !~ '[[:cntrl:]]'
    )
);

CREATE TABLE source.tmdb_v3_list_items (
    list_id bigint NOT NULL REFERENCES source.tmdb_v3_lists(id) ON DELETE CASCADE,
    media_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (list_id, media_id),
    CONSTRAINT tmdb_v3_list_items_media_id_check CHECK (media_id > 0)
);

CREATE TABLE source.tmdb_v3_account_items (
    account_id bigint NOT NULL,
    relation text NOT NULL,
    media_type text NOT NULL,
    media_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (account_id, relation, media_type, media_id),
    CONSTRAINT tmdb_v3_account_items_relation_check CHECK (
        relation IN ('favorite', 'watchlist')
    ),
    CONSTRAINT tmdb_v3_account_items_media_type_check CHECK (
        media_type IN ('movie', 'tv')
    ),
    CONSTRAINT tmdb_v3_account_items_media_id_check CHECK (media_id > 0)
);

CREATE TABLE source.tmdb_v3_ratings (
    owner_kind text NOT NULL,
    owner_id text NOT NULL,
    media_type text NOT NULL,
    media_id bigint NOT NULL,
    season_number integer NOT NULL DEFAULT 0,
    episode_number integer NOT NULL DEFAULT 0,
    rating double precision NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    PRIMARY KEY (
        owner_kind, owner_id, media_type, media_id, season_number, episode_number
    ),
    CONSTRAINT tmdb_v3_ratings_owner_kind_check CHECK (
        owner_kind IN ('session', 'guest')
    ),
    CONSTRAINT tmdb_v3_ratings_owner_id_check CHECK (
        pg_catalog.char_length(owner_id) BETWEEN 1 AND 128
        AND owner_id !~ '[[:cntrl:]]'
    ),
    CONSTRAINT tmdb_v3_ratings_media_type_check CHECK (
        media_type IN ('movie', 'tv', 'tv_episode')
    ),
    CONSTRAINT tmdb_v3_ratings_media_id_check CHECK (media_id > 0),
    CONSTRAINT tmdb_v3_ratings_location_check CHECK (
        (media_type = 'tv_episode' AND season_number > 0 AND episode_number > 0)
        OR (media_type IN ('movie', 'tv') AND season_number = 0 AND episode_number = 0)
    ),
    CONSTRAINT tmdb_v3_ratings_value_check CHECK (rating >= 0.5 AND rating <= 10.0)
);

ALTER TABLE source.tmdb_v3_request_tokens OWNER TO migrator;
ALTER TABLE source.tmdb_v3_sessions OWNER TO migrator;
ALTER TABLE source.tmdb_v3_lists OWNER TO migrator;
ALTER TABLE source.tmdb_v3_list_items OWNER TO migrator;
ALTER TABLE source.tmdb_v3_account_items OWNER TO migrator;
ALTER TABLE source.tmdb_v3_ratings OWNER TO migrator;

GRANT SELECT ON TABLE
    source.tmdb_v3_request_tokens,
    source.tmdb_v3_sessions,
    source.tmdb_v3_lists,
    source.tmdb_v3_list_items,
    source.tmdb_v3_account_items,
    source.tmdb_v3_ratings
    TO api_reader, monitor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    source.tmdb_v3_request_tokens,
    source.tmdb_v3_sessions,
    source.tmdb_v3_lists,
    source.tmdb_v3_list_items,
    source.tmdb_v3_account_items,
    source.tmdb_v3_ratings
    TO api_job_submitter;
GRANT USAGE, SELECT ON SEQUENCE source.tmdb_v3_lists_id_seq TO api_job_submitter;

UPDATE ops.service_metadata
SET value = pg_catalog.jsonb_build_object(
        'revision', '0035',
        'migrated_at', pg_catalog.to_char(
            pg_catalog.clock_timestamp() AT TIME ZONE 'UTC',
            'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'
        )
    ),
    updated_at = pg_catalog.clock_timestamp()
WHERE key = 'schema';

CREATE OR REPLACE VIEW ops.readiness AS
SELECT metadata.value ->> 'revision' AS schema_revision,
       (metadata.value ->> 'migrated_at')::timestamptz AS migrated_at
FROM ops.service_metadata AS metadata
WHERE metadata.key = 'schema'
  AND metadata.value ->> 'revision' = '0035'
  AND (SELECT pg_catalog.count(*) FROM ops._sqlx_migrations) = 35
  AND (
      SELECT pg_catalog.array_agg(migration.version ORDER BY migration.version)
      FROM ops._sqlx_migrations AS migration
      WHERE migration.success
  ) = ARRAY[
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
      21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
  ]::bigint[]
  AND NOT EXISTS (
      SELECT 1
      FROM ops._sqlx_migrations AS migration
      WHERE NOT migration.success
  );

ALTER VIEW ops.readiness OWNER TO migrator;
REVOKE ALL ON TABLE ops.readiness
    FROM PUBLIC, api_reader, api_job_submitter, ingest_writer, image_writer, monitor;
GRANT SELECT ON TABLE ops.readiness TO api_reader, monitor;
